quicksort.cpp
gaurav03kr/gauravfirst pull request #12
Opened 2022-10-14 05:19 UTC by githubPrabhsingh

2022-10-15 07:51 UTC, gaurav03kr requested changes
Remove line 2 and all code corresponds to it.

2022-10-15 09:34 UTC, githubPrabhsingh commented
change done .


On Sat, Oct 15, 2022 at 1:21 PM gaurav03kr ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Remove line 2 and all code corresponds to it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gaurav03kr/gauravfirst/pull/12#pullrequestreview-1143155604>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYHFBXJJ2NPIIA7KBEYQBOLWDJO7TANCNFSM6AAAAAARE4TCMY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-15 16:05 UTC, gaurav03kr approved these changes

2022-10-15 16:05 UTC, merged

2022-10-16 05:31 UTC, githubPrabhsingh commented
Thankyou !!

On Sat, Oct 15, 2022, 21:36 gaurav03kr ***@***.***> wrote:

> Merged #12 <https://github.com/gaurav03kr/gauravfirst/pull/12> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gaurav03kr/gauravfirst/pull/12#event-7595178324>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYHFBXIBQQ7W74DXSUVGIFDWDLI7FANCNFSM6AAAAAARE4TCMY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>